//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type Attendance struct {
	ID           int32 `sql:"primary_key"`
	EmployeeId   uuid.UUID
	Date         time.Time
	CheckInTime  *time.Time
	CheckOutTime *time.Time
	Status       *string
	WorkHours    *decimal.Decimal
	Remarks      *string
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	MarkedBy     *uuid.UUID
}
