//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Attendance struct {
	ID              int32 `sql:"primary_key"`
	EmployeeId      uuid.UUID
	Date            time.Time
	CheckInTime     *time.Time
	CheckOutTime    *time.Time
	Status          *string
	WorkHours       *time.Time
	Remarks         *string
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
	MarkedBy        *uuid.UUID
	LateByMinutes   *int32
	EarlyByMinutes  *int32
	OvertimeMinutes *int32
	Shift           *string
}
