//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type EmployeeLeaveBalance struct {
	ID                 uuid.UUID `sql:"primary_key"`
	EmployeeId         uuid.UUID
	LeaveTypeId        uuid.UUID
	Year               int32
	TotalDays          decimal.Decimal
	UsedDays           decimal.Decimal
	RemainingDays      decimal.Decimal
	CarriedForwardDays decimal.Decimal
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
