//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type LeaveApproval struct {
	ID                 uuid.UUID `sql:"primary_key"`
	LeaveApplicationId uuid.UUID
	EmployeeId         uuid.UUID
	ApproverId         uuid.UUID
	ApprovalLevel      int32
	Action             string
	Comments           *string
	ActionAt           *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
