//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type LeaveType struct {
	ID                  uuid.UUID `sql:"primary_key"`
	Name                string
	Description         *string
	MaxDaysPerYear      int32
	IsCarryForward      bool
	MaxCarryForwardDays int32
	OrganizationId      uuid.UUID
	IsActive            bool
	CreatedAt           time.Time
	CreatedBy           *uuid.UUID
}
