//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type LeavePolicy struct {
	ID                  uuid.UUID `sql:"primary_key"`
	Name                string
	LeaveTypeId         uuid.UUID
	AnnualLimit         decimal.Decimal
	MaxConsecutiveDays  decimal.Decimal
	CarryForward        bool
	MaxCarryForwardDays decimal.Decimal
	RequiresApproval    bool
	EffectiveFrom       time.Time
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
