//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Regularization struct {
	ID                uuid.UUID `sql:"primary_key"`
	EmployeeId        uuid.UUID
	AttendanceId      int32
	RequestedCheckIn  *time.Time
	RequestedCheckOut *time.Time
	Reason            string
	Status            string
	ApprovedBy        *uuid.UUID
	ApprovedAt        *time.Time
	RejectionReason   *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
