//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type SalaryStructure struct {
	ID            uuid.UUID `sql:"primary_key"`
	EmployeeId    uuid.UUID
	EffectiveFrom time.Time
	EffectiveTo   *time.Time
	BasicSalary   decimal.Decimal
	Hra           decimal.Decimal
	Allowances    string
	Deductions    string
	GrossSalary   decimal.Decimal
	NetSalary     decimal.Decimal
	Currency      string
	CreatedAt     time.Time
	CreatedBy     *uuid.UUID
	UpdatedAt     time.Time
}
