//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type SalaryStructure struct {
	ID              uuid.UUID `sql:"primary_key"`
	EmployeeId      uuid.UUID
	GrossSalary     decimal.Decimal
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EmployeeName    *string
	DateOfJoining   *time.Time
	CtcPerMonth     *decimal.Decimal
	DaysPaid        *decimal.Decimal
	Salary          *decimal.Decimal
	Late            *decimal.Decimal
	Incentive       *decimal.Decimal
	Conv            *decimal.Decimal
	Advance         *decimal.Decimal
	DeductionAmount *decimal.Decimal
	AccountNo       *string
	Ifsc            *string
	PfDeduction     *decimal.Decimal
	PfUanNumber     *string
	Location        *string
}
