//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Attendance = newAttendanceTable("public", "Attendance", "")

type attendanceTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	EmployeeId   postgres.ColumnString
	Date         postgres.ColumnDate
	CheckInTime  postgres.ColumnTimestampz
	CheckOutTime postgres.ColumnTimestampz
	Status       postgres.ColumnString
	WorkHours    postgres.ColumnFloat
	Remarks      postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz
	MarkedBy     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AttendanceTable struct {
	attendanceTable

	EXCLUDED attendanceTable
}

// AS creates new AttendanceTable with assigned alias
func (a AttendanceTable) AS(alias string) *AttendanceTable {
	return newAttendanceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AttendanceTable with assigned schema name
func (a AttendanceTable) FromSchema(schemaName string) *AttendanceTable {
	return newAttendanceTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AttendanceTable with assigned table prefix
func (a AttendanceTable) WithPrefix(prefix string) *AttendanceTable {
	return newAttendanceTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AttendanceTable with assigned table suffix
func (a AttendanceTable) WithSuffix(suffix string) *AttendanceTable {
	return newAttendanceTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAttendanceTable(schemaName, tableName, alias string) *AttendanceTable {
	return &AttendanceTable{
		attendanceTable: newAttendanceTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newAttendanceTableImpl("", "excluded", ""),
	}
}

func newAttendanceTableImpl(schemaName, tableName, alias string) attendanceTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		EmployeeIdColumn   = postgres.StringColumn("employeeId")
		DateColumn         = postgres.DateColumn("date")
		CheckInTimeColumn  = postgres.TimestampzColumn("checkInTime")
		CheckOutTimeColumn = postgres.TimestampzColumn("checkOutTime")
		StatusColumn       = postgres.StringColumn("status")
		WorkHoursColumn    = postgres.FloatColumn("workHours")
		RemarksColumn      = postgres.StringColumn("remarks")
		CreatedAtColumn    = postgres.TimestampzColumn("createdAt")
		UpdatedAtColumn    = postgres.TimestampzColumn("updatedAt")
		MarkedByColumn     = postgres.StringColumn("markedBy")
		allColumns         = postgres.ColumnList{IDColumn, EmployeeIdColumn, DateColumn, CheckInTimeColumn, CheckOutTimeColumn, StatusColumn, WorkHoursColumn, RemarksColumn, CreatedAtColumn, UpdatedAtColumn, MarkedByColumn}
		mutableColumns     = postgres.ColumnList{EmployeeIdColumn, DateColumn, CheckInTimeColumn, CheckOutTimeColumn, StatusColumn, WorkHoursColumn, RemarksColumn, CreatedAtColumn, UpdatedAtColumn, MarkedByColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, DateColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return attendanceTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		EmployeeId:   EmployeeIdColumn,
		Date:         DateColumn,
		CheckInTime:  CheckInTimeColumn,
		CheckOutTime: CheckOutTimeColumn,
		Status:       StatusColumn,
		WorkHours:    WorkHoursColumn,
		Remarks:      RemarksColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		MarkedBy:     MarkedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
