//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmployeeLeaveBalance = newEmployeeLeaveBalanceTable("public", "EmployeeLeaveBalance", "")

type employeeLeaveBalanceTable struct {
	postgres.Table

	// Columns
	ID                 postgres.ColumnString
	EmployeeId         postgres.ColumnString
	LeaveTypeId        postgres.ColumnString
	Year               postgres.ColumnInteger
	TotalDays          postgres.ColumnFloat
	UsedDays           postgres.ColumnFloat
	RemainingDays      postgres.ColumnFloat
	CarriedForwardDays postgres.ColumnFloat
	CreatedAt          postgres.ColumnTimestamp
	UpdatedAt          postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmployeeLeaveBalanceTable struct {
	employeeLeaveBalanceTable

	EXCLUDED employeeLeaveBalanceTable
}

// AS creates new EmployeeLeaveBalanceTable with assigned alias
func (a EmployeeLeaveBalanceTable) AS(alias string) *EmployeeLeaveBalanceTable {
	return newEmployeeLeaveBalanceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmployeeLeaveBalanceTable with assigned schema name
func (a EmployeeLeaveBalanceTable) FromSchema(schemaName string) *EmployeeLeaveBalanceTable {
	return newEmployeeLeaveBalanceTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmployeeLeaveBalanceTable with assigned table prefix
func (a EmployeeLeaveBalanceTable) WithPrefix(prefix string) *EmployeeLeaveBalanceTable {
	return newEmployeeLeaveBalanceTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmployeeLeaveBalanceTable with assigned table suffix
func (a EmployeeLeaveBalanceTable) WithSuffix(suffix string) *EmployeeLeaveBalanceTable {
	return newEmployeeLeaveBalanceTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmployeeLeaveBalanceTable(schemaName, tableName, alias string) *EmployeeLeaveBalanceTable {
	return &EmployeeLeaveBalanceTable{
		employeeLeaveBalanceTable: newEmployeeLeaveBalanceTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newEmployeeLeaveBalanceTableImpl("", "excluded", ""),
	}
}

func newEmployeeLeaveBalanceTableImpl(schemaName, tableName, alias string) employeeLeaveBalanceTable {
	var (
		IDColumn                 = postgres.StringColumn("id")
		EmployeeIdColumn         = postgres.StringColumn("employeeId")
		LeaveTypeIdColumn        = postgres.StringColumn("leaveTypeId")
		YearColumn               = postgres.IntegerColumn("year")
		TotalDaysColumn          = postgres.FloatColumn("totalDays")
		UsedDaysColumn           = postgres.FloatColumn("usedDays")
		RemainingDaysColumn      = postgres.FloatColumn("remainingDays")
		CarriedForwardDaysColumn = postgres.FloatColumn("carriedForwardDays")
		CreatedAtColumn          = postgres.TimestampColumn("createdAt")
		UpdatedAtColumn          = postgres.TimestampColumn("updatedAt")
		allColumns               = postgres.ColumnList{IDColumn, EmployeeIdColumn, LeaveTypeIdColumn, YearColumn, TotalDaysColumn, UsedDaysColumn, RemainingDaysColumn, CarriedForwardDaysColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns           = postgres.ColumnList{EmployeeIdColumn, LeaveTypeIdColumn, YearColumn, TotalDaysColumn, UsedDaysColumn, RemainingDaysColumn, CarriedForwardDaysColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDColumn, TotalDaysColumn, UsedDaysColumn, RemainingDaysColumn, CarriedForwardDaysColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return employeeLeaveBalanceTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		EmployeeId:         EmployeeIdColumn,
		LeaveTypeId:        LeaveTypeIdColumn,
		Year:               YearColumn,
		TotalDays:          TotalDaysColumn,
		UsedDays:           UsedDaysColumn,
		RemainingDays:      RemainingDaysColumn,
		CarriedForwardDays: CarriedForwardDaysColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
