//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LeaveApproval = newLeaveApprovalTable("public", "LeaveApproval", "")

type leaveApprovalTable struct {
	postgres.Table

	// Columns
	ID                 postgres.ColumnString
	LeaveApplicationId postgres.ColumnString
	EmployeeId         postgres.ColumnString
	ApproverId         postgres.ColumnString
	ApprovalLevel      postgres.ColumnInteger
	Action             postgres.ColumnString
	Comments           postgres.ColumnString
	ActionAt           postgres.ColumnTimestampz
	CreatedAt          postgres.ColumnTimestampz
	UpdatedAt          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LeaveApprovalTable struct {
	leaveApprovalTable

	EXCLUDED leaveApprovalTable
}

// AS creates new LeaveApprovalTable with assigned alias
func (a LeaveApprovalTable) AS(alias string) *LeaveApprovalTable {
	return newLeaveApprovalTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LeaveApprovalTable with assigned schema name
func (a LeaveApprovalTable) FromSchema(schemaName string) *LeaveApprovalTable {
	return newLeaveApprovalTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LeaveApprovalTable with assigned table prefix
func (a LeaveApprovalTable) WithPrefix(prefix string) *LeaveApprovalTable {
	return newLeaveApprovalTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LeaveApprovalTable with assigned table suffix
func (a LeaveApprovalTable) WithSuffix(suffix string) *LeaveApprovalTable {
	return newLeaveApprovalTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLeaveApprovalTable(schemaName, tableName, alias string) *LeaveApprovalTable {
	return &LeaveApprovalTable{
		leaveApprovalTable: newLeaveApprovalTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newLeaveApprovalTableImpl("", "excluded", ""),
	}
}

func newLeaveApprovalTableImpl(schemaName, tableName, alias string) leaveApprovalTable {
	var (
		IDColumn                 = postgres.StringColumn("id")
		LeaveApplicationIdColumn = postgres.StringColumn("leaveApplicationId")
		EmployeeIdColumn         = postgres.StringColumn("employeeId")
		ApproverIdColumn         = postgres.StringColumn("approverId")
		ApprovalLevelColumn      = postgres.IntegerColumn("approvalLevel")
		ActionColumn             = postgres.StringColumn("action")
		CommentsColumn           = postgres.StringColumn("comments")
		ActionAtColumn           = postgres.TimestampzColumn("actionAt")
		CreatedAtColumn          = postgres.TimestampzColumn("createdAt")
		UpdatedAtColumn          = postgres.TimestampzColumn("updatedAt")
		allColumns               = postgres.ColumnList{IDColumn, LeaveApplicationIdColumn, EmployeeIdColumn, ApproverIdColumn, ApprovalLevelColumn, ActionColumn, CommentsColumn, ActionAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns           = postgres.ColumnList{LeaveApplicationIdColumn, EmployeeIdColumn, ApproverIdColumn, ApprovalLevelColumn, ActionColumn, CommentsColumn, ActionAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns           = postgres.ColumnList{IDColumn, ApprovalLevelColumn, ActionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return leaveApprovalTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		LeaveApplicationId: LeaveApplicationIdColumn,
		EmployeeId:         EmployeeIdColumn,
		ApproverId:         ApproverIdColumn,
		ApprovalLevel:      ApprovalLevelColumn,
		Action:             ActionColumn,
		Comments:           CommentsColumn,
		ActionAt:           ActionAtColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
