//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LeaveType = newLeaveTypeTable("public", "LeaveType", "")

type leaveTypeTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	Name                postgres.ColumnString
	Description         postgres.ColumnString
	MaxDaysPerYear      postgres.ColumnInteger
	IsCarryForward      postgres.ColumnBool
	MaxCarryForwardDays postgres.ColumnInteger
	OrganizationId      postgres.ColumnString
	IsActive            postgres.ColumnBool
	CreatedAt           postgres.ColumnTimestamp
	CreatedBy           postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LeaveTypeTable struct {
	leaveTypeTable

	EXCLUDED leaveTypeTable
}

// AS creates new LeaveTypeTable with assigned alias
func (a LeaveTypeTable) AS(alias string) *LeaveTypeTable {
	return newLeaveTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LeaveTypeTable with assigned schema name
func (a LeaveTypeTable) FromSchema(schemaName string) *LeaveTypeTable {
	return newLeaveTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LeaveTypeTable with assigned table prefix
func (a LeaveTypeTable) WithPrefix(prefix string) *LeaveTypeTable {
	return newLeaveTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LeaveTypeTable with assigned table suffix
func (a LeaveTypeTable) WithSuffix(suffix string) *LeaveTypeTable {
	return newLeaveTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLeaveTypeTable(schemaName, tableName, alias string) *LeaveTypeTable {
	return &LeaveTypeTable{
		leaveTypeTable: newLeaveTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newLeaveTypeTableImpl("", "excluded", ""),
	}
}

func newLeaveTypeTableImpl(schemaName, tableName, alias string) leaveTypeTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		NameColumn                = postgres.StringColumn("name")
		DescriptionColumn         = postgres.StringColumn("description")
		MaxDaysPerYearColumn      = postgres.IntegerColumn("maxDaysPerYear")
		IsCarryForwardColumn      = postgres.BoolColumn("isCarryForward")
		MaxCarryForwardDaysColumn = postgres.IntegerColumn("maxCarryForwardDays")
		OrganizationIdColumn      = postgres.StringColumn("organizationId")
		IsActiveColumn            = postgres.BoolColumn("isActive")
		CreatedAtColumn           = postgres.TimestampColumn("createdAt")
		CreatedByColumn           = postgres.StringColumn("createdBy")
		allColumns                = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, MaxDaysPerYearColumn, IsCarryForwardColumn, MaxCarryForwardDaysColumn, OrganizationIdColumn, IsActiveColumn, CreatedAtColumn, CreatedByColumn}
		mutableColumns            = postgres.ColumnList{NameColumn, DescriptionColumn, MaxDaysPerYearColumn, IsCarryForwardColumn, MaxCarryForwardDaysColumn, OrganizationIdColumn, IsActiveColumn, CreatedAtColumn, CreatedByColumn}
		defaultColumns            = postgres.ColumnList{IDColumn, IsCarryForwardColumn, MaxCarryForwardDaysColumn, IsActiveColumn, CreatedAtColumn}
	)

	return leaveTypeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		Name:                NameColumn,
		Description:         DescriptionColumn,
		MaxDaysPerYear:      MaxDaysPerYearColumn,
		IsCarryForward:      IsCarryForwardColumn,
		MaxCarryForwardDays: MaxCarryForwardDaysColumn,
		OrganizationId:      OrganizationIdColumn,
		IsActive:            IsActiveColumn,
		CreatedAt:           CreatedAtColumn,
		CreatedBy:           CreatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
