//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LeaveApplication = newLeaveApplicationTable("public", "LeaveApplication", "")

type leaveApplicationTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	EmployeeId      postgres.ColumnString
	LeaveTypeId     postgres.ColumnString
	StartDate       postgres.ColumnDate
	EndDate         postgres.ColumnDate
	TotalDays       postgres.ColumnFloat
	Reason          postgres.ColumnString
	Status          postgres.ColumnString
	AppliedAt       postgres.ColumnTimestamp
	ApprovedBy      postgres.ColumnString
	ApprovedAt      postgres.ColumnTimestamp
	RejectionReason postgres.ColumnString
	CancelledAt     postgres.ColumnTimestamp
	CancelledBy     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LeaveApplicationTable struct {
	leaveApplicationTable

	EXCLUDED leaveApplicationTable
}

// AS creates new LeaveApplicationTable with assigned alias
func (a LeaveApplicationTable) AS(alias string) *LeaveApplicationTable {
	return newLeaveApplicationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LeaveApplicationTable with assigned schema name
func (a LeaveApplicationTable) FromSchema(schemaName string) *LeaveApplicationTable {
	return newLeaveApplicationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LeaveApplicationTable with assigned table prefix
func (a LeaveApplicationTable) WithPrefix(prefix string) *LeaveApplicationTable {
	return newLeaveApplicationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LeaveApplicationTable with assigned table suffix
func (a LeaveApplicationTable) WithSuffix(suffix string) *LeaveApplicationTable {
	return newLeaveApplicationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLeaveApplicationTable(schemaName, tableName, alias string) *LeaveApplicationTable {
	return &LeaveApplicationTable{
		leaveApplicationTable: newLeaveApplicationTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newLeaveApplicationTableImpl("", "excluded", ""),
	}
}

func newLeaveApplicationTableImpl(schemaName, tableName, alias string) leaveApplicationTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		EmployeeIdColumn      = postgres.StringColumn("employeeId")
		LeaveTypeIdColumn     = postgres.StringColumn("leaveTypeId")
		StartDateColumn       = postgres.DateColumn("startDate")
		EndDateColumn         = postgres.DateColumn("endDate")
		TotalDaysColumn       = postgres.FloatColumn("totalDays")
		ReasonColumn          = postgres.StringColumn("reason")
		StatusColumn          = postgres.StringColumn("status")
		AppliedAtColumn       = postgres.TimestampColumn("appliedAt")
		ApprovedByColumn      = postgres.StringColumn("approvedBy")
		ApprovedAtColumn      = postgres.TimestampColumn("approvedAt")
		RejectionReasonColumn = postgres.StringColumn("rejectionReason")
		CancelledAtColumn     = postgres.TimestampColumn("cancelledAt")
		CancelledByColumn     = postgres.StringColumn("cancelledBy")
		allColumns            = postgres.ColumnList{IDColumn, EmployeeIdColumn, LeaveTypeIdColumn, StartDateColumn, EndDateColumn, TotalDaysColumn, ReasonColumn, StatusColumn, AppliedAtColumn, ApprovedByColumn, ApprovedAtColumn, RejectionReasonColumn, CancelledAtColumn, CancelledByColumn}
		mutableColumns        = postgres.ColumnList{EmployeeIdColumn, LeaveTypeIdColumn, StartDateColumn, EndDateColumn, TotalDaysColumn, ReasonColumn, StatusColumn, AppliedAtColumn, ApprovedByColumn, ApprovedAtColumn, RejectionReasonColumn, CancelledAtColumn, CancelledByColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, StatusColumn, AppliedAtColumn}
	)

	return leaveApplicationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		EmployeeId:      EmployeeIdColumn,
		LeaveTypeId:     LeaveTypeIdColumn,
		StartDate:       StartDateColumn,
		EndDate:         EndDateColumn,
		TotalDays:       TotalDaysColumn,
		Reason:          ReasonColumn,
		Status:          StatusColumn,
		AppliedAt:       AppliedAtColumn,
		ApprovedBy:      ApprovedByColumn,
		ApprovedAt:      ApprovedAtColumn,
		RejectionReason: RejectionReasonColumn,
		CancelledAt:     CancelledAtColumn,
		CancelledBy:     CancelledByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
