//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LeavePolicy = newLeavePolicyTable("public", "LeavePolicy", "")

type leavePolicyTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	Name                postgres.ColumnString
	LeaveTypeId         postgres.ColumnString
	AnnualLimit         postgres.ColumnFloat
	MaxConsecutiveDays  postgres.ColumnFloat
	CarryForward        postgres.ColumnBool
	MaxCarryForwardDays postgres.ColumnFloat
	RequiresApproval    postgres.ColumnBool
	EffectiveFrom       postgres.ColumnDate
	Status              postgres.ColumnString
	CreatedAt           postgres.ColumnTimestamp
	UpdatedAt           postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LeavePolicyTable struct {
	leavePolicyTable

	EXCLUDED leavePolicyTable
}

// AS creates new LeavePolicyTable with assigned alias
func (a LeavePolicyTable) AS(alias string) *LeavePolicyTable {
	return newLeavePolicyTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LeavePolicyTable with assigned schema name
func (a LeavePolicyTable) FromSchema(schemaName string) *LeavePolicyTable {
	return newLeavePolicyTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LeavePolicyTable with assigned table prefix
func (a LeavePolicyTable) WithPrefix(prefix string) *LeavePolicyTable {
	return newLeavePolicyTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LeavePolicyTable with assigned table suffix
func (a LeavePolicyTable) WithSuffix(suffix string) *LeavePolicyTable {
	return newLeavePolicyTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLeavePolicyTable(schemaName, tableName, alias string) *LeavePolicyTable {
	return &LeavePolicyTable{
		leavePolicyTable: newLeavePolicyTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newLeavePolicyTableImpl("", "excluded", ""),
	}
}

func newLeavePolicyTableImpl(schemaName, tableName, alias string) leavePolicyTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		NameColumn                = postgres.StringColumn("name")
		LeaveTypeIdColumn         = postgres.StringColumn("leaveTypeId")
		AnnualLimitColumn         = postgres.FloatColumn("annualLimit")
		MaxConsecutiveDaysColumn  = postgres.FloatColumn("maxConsecutiveDays")
		CarryForwardColumn        = postgres.BoolColumn("carryForward")
		MaxCarryForwardDaysColumn = postgres.FloatColumn("maxCarryForwardDays")
		RequiresApprovalColumn    = postgres.BoolColumn("requiresApproval")
		EffectiveFromColumn       = postgres.DateColumn("effectiveFrom")
		StatusColumn              = postgres.StringColumn("status")
		CreatedAtColumn           = postgres.TimestampColumn("createdAt")
		UpdatedAtColumn           = postgres.TimestampColumn("updatedAt")
		allColumns                = postgres.ColumnList{IDColumn, NameColumn, LeaveTypeIdColumn, AnnualLimitColumn, MaxConsecutiveDaysColumn, CarryForwardColumn, MaxCarryForwardDaysColumn, RequiresApprovalColumn, EffectiveFromColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns            = postgres.ColumnList{NameColumn, LeaveTypeIdColumn, AnnualLimitColumn, MaxConsecutiveDaysColumn, CarryForwardColumn, MaxCarryForwardDaysColumn, RequiresApprovalColumn, EffectiveFromColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns            = postgres.ColumnList{IDColumn, CarryForwardColumn, MaxCarryForwardDaysColumn, RequiresApprovalColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return leavePolicyTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		Name:                NameColumn,
		LeaveTypeId:         LeaveTypeIdColumn,
		AnnualLimit:         AnnualLimitColumn,
		MaxConsecutiveDays:  MaxConsecutiveDaysColumn,
		CarryForward:        CarryForwardColumn,
		MaxCarryForwardDays: MaxCarryForwardDaysColumn,
		RequiresApproval:    RequiresApprovalColumn,
		EffectiveFrom:       EffectiveFromColumn,
		Status:              StatusColumn,
		CreatedAt:           CreatedAtColumn,
		UpdatedAt:           UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
