//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Regularization = newRegularizationTable("public", "Regularization", "")

type regularizationTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	EmployeeId        postgres.ColumnString
	AttendanceId      postgres.ColumnInteger
	RequestedCheckIn  postgres.ColumnTimestampz
	RequestedCheckOut postgres.ColumnTimestampz
	Reason            postgres.ColumnString
	Status            postgres.ColumnString
	ApprovedBy        postgres.ColumnString
	ApprovedAt        postgres.ColumnTimestampz
	RejectionReason   postgres.ColumnString
	CreatedAt         postgres.ColumnTimestamp
	UpdatedAt         postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RegularizationTable struct {
	regularizationTable

	EXCLUDED regularizationTable
}

// AS creates new RegularizationTable with assigned alias
func (a RegularizationTable) AS(alias string) *RegularizationTable {
	return newRegularizationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RegularizationTable with assigned schema name
func (a RegularizationTable) FromSchema(schemaName string) *RegularizationTable {
	return newRegularizationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RegularizationTable with assigned table prefix
func (a RegularizationTable) WithPrefix(prefix string) *RegularizationTable {
	return newRegularizationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RegularizationTable with assigned table suffix
func (a RegularizationTable) WithSuffix(suffix string) *RegularizationTable {
	return newRegularizationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRegularizationTable(schemaName, tableName, alias string) *RegularizationTable {
	return &RegularizationTable{
		regularizationTable: newRegularizationTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newRegularizationTableImpl("", "excluded", ""),
	}
}

func newRegularizationTableImpl(schemaName, tableName, alias string) regularizationTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		EmployeeIdColumn        = postgres.StringColumn("employeeId")
		AttendanceIdColumn      = postgres.IntegerColumn("attendanceId")
		RequestedCheckInColumn  = postgres.TimestampzColumn("requestedCheckIn")
		RequestedCheckOutColumn = postgres.TimestampzColumn("requestedCheckOut")
		ReasonColumn            = postgres.StringColumn("reason")
		StatusColumn            = postgres.StringColumn("status")
		ApprovedByColumn        = postgres.StringColumn("approvedBy")
		ApprovedAtColumn        = postgres.TimestampzColumn("approvedAt")
		RejectionReasonColumn   = postgres.StringColumn("rejectionReason")
		CreatedAtColumn         = postgres.TimestampColumn("createdAt")
		UpdatedAtColumn         = postgres.TimestampColumn("updatedAt")
		allColumns              = postgres.ColumnList{IDColumn, EmployeeIdColumn, AttendanceIdColumn, RequestedCheckInColumn, RequestedCheckOutColumn, ReasonColumn, StatusColumn, ApprovedByColumn, ApprovedAtColumn, RejectionReasonColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{EmployeeIdColumn, AttendanceIdColumn, RequestedCheckInColumn, RequestedCheckOutColumn, ReasonColumn, StatusColumn, ApprovedByColumn, ApprovedAtColumn, RejectionReasonColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return regularizationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		EmployeeId:        EmployeeIdColumn,
		AttendanceId:      AttendanceIdColumn,
		RequestedCheckIn:  RequestedCheckInColumn,
		RequestedCheckOut: RequestedCheckOutColumn,
		Reason:            ReasonColumn,
		Status:            StatusColumn,
		ApprovedBy:        ApprovedByColumn,
		ApprovedAt:        ApprovedAtColumn,
		RejectionReason:   RejectionReasonColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
