//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SalaryStructure = newSalaryStructureTable("public", "SalaryStructure", "")

type salaryStructureTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	EmployeeId    postgres.ColumnString
	EffectiveFrom postgres.ColumnDate
	EffectiveTo   postgres.ColumnDate
	BasicSalary   postgres.ColumnFloat
	Hra           postgres.ColumnFloat
	Allowances    postgres.ColumnString
	Deductions    postgres.ColumnString
	GrossSalary   postgres.ColumnFloat
	NetSalary     postgres.ColumnFloat
	Currency      postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	CreatedBy     postgres.ColumnString
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SalaryStructureTable struct {
	salaryStructureTable

	EXCLUDED salaryStructureTable
}

// AS creates new SalaryStructureTable with assigned alias
func (a SalaryStructureTable) AS(alias string) *SalaryStructureTable {
	return newSalaryStructureTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SalaryStructureTable with assigned schema name
func (a SalaryStructureTable) FromSchema(schemaName string) *SalaryStructureTable {
	return newSalaryStructureTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SalaryStructureTable with assigned table prefix
func (a SalaryStructureTable) WithPrefix(prefix string) *SalaryStructureTable {
	return newSalaryStructureTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SalaryStructureTable with assigned table suffix
func (a SalaryStructureTable) WithSuffix(suffix string) *SalaryStructureTable {
	return newSalaryStructureTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSalaryStructureTable(schemaName, tableName, alias string) *SalaryStructureTable {
	return &SalaryStructureTable{
		salaryStructureTable: newSalaryStructureTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newSalaryStructureTableImpl("", "excluded", ""),
	}
}

func newSalaryStructureTableImpl(schemaName, tableName, alias string) salaryStructureTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		EmployeeIdColumn    = postgres.StringColumn("employeeId")
		EffectiveFromColumn = postgres.DateColumn("effectiveFrom")
		EffectiveToColumn   = postgres.DateColumn("effectiveTo")
		BasicSalaryColumn   = postgres.FloatColumn("basicSalary")
		HraColumn           = postgres.FloatColumn("hra")
		AllowancesColumn    = postgres.StringColumn("allowances")
		DeductionsColumn    = postgres.StringColumn("deductions")
		GrossSalaryColumn   = postgres.FloatColumn("grossSalary")
		NetSalaryColumn     = postgres.FloatColumn("netSalary")
		CurrencyColumn      = postgres.StringColumn("currency")
		CreatedAtColumn     = postgres.TimestampColumn("createdAt")
		CreatedByColumn     = postgres.StringColumn("createdBy")
		UpdatedAtColumn     = postgres.TimestampColumn("updatedAt")
		allColumns          = postgres.ColumnList{IDColumn, EmployeeIdColumn, EffectiveFromColumn, EffectiveToColumn, BasicSalaryColumn, HraColumn, AllowancesColumn, DeductionsColumn, GrossSalaryColumn, NetSalaryColumn, CurrencyColumn, CreatedAtColumn, CreatedByColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{EmployeeIdColumn, EffectiveFromColumn, EffectiveToColumn, BasicSalaryColumn, HraColumn, AllowancesColumn, DeductionsColumn, GrossSalaryColumn, NetSalaryColumn, CurrencyColumn, CreatedAtColumn, CreatedByColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, BasicSalaryColumn, HraColumn, AllowancesColumn, DeductionsColumn, GrossSalaryColumn, NetSalaryColumn, CurrencyColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return salaryStructureTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		EmployeeId:    EmployeeIdColumn,
		EffectiveFrom: EffectiveFromColumn,
		EffectiveTo:   EffectiveToColumn,
		BasicSalary:   BasicSalaryColumn,
		Hra:           HraColumn,
		Allowances:    AllowancesColumn,
		Deductions:    DeductionsColumn,
		GrossSalary:   GrossSalaryColumn,
		NetSalary:     NetSalaryColumn,
		Currency:      CurrencyColumn,
		CreatedAt:     CreatedAtColumn,
		CreatedBy:     CreatedByColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
