//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SalaryStructure = newSalaryStructureTable("public", "SalaryStructure", "")

type salaryStructureTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	EmployeeId      postgres.ColumnString
	GrossSalary     postgres.ColumnFloat
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp
	EmployeeName    postgres.ColumnString
	DateOfJoining   postgres.ColumnDate
	CtcPerMonth     postgres.ColumnFloat
	DaysPaid        postgres.ColumnFloat
	Salary          postgres.ColumnFloat
	Late            postgres.ColumnFloat
	Incentive       postgres.ColumnFloat
	Conv            postgres.ColumnFloat
	Advance         postgres.ColumnFloat
	DeductionAmount postgres.ColumnFloat
	AccountNo       postgres.ColumnString
	Ifsc            postgres.ColumnString
	PfDeduction     postgres.ColumnFloat
	PfUanNumber     postgres.ColumnString
	Location        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SalaryStructureTable struct {
	salaryStructureTable

	EXCLUDED salaryStructureTable
}

// AS creates new SalaryStructureTable with assigned alias
func (a SalaryStructureTable) AS(alias string) *SalaryStructureTable {
	return newSalaryStructureTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SalaryStructureTable with assigned schema name
func (a SalaryStructureTable) FromSchema(schemaName string) *SalaryStructureTable {
	return newSalaryStructureTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SalaryStructureTable with assigned table prefix
func (a SalaryStructureTable) WithPrefix(prefix string) *SalaryStructureTable {
	return newSalaryStructureTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SalaryStructureTable with assigned table suffix
func (a SalaryStructureTable) WithSuffix(suffix string) *SalaryStructureTable {
	return newSalaryStructureTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSalaryStructureTable(schemaName, tableName, alias string) *SalaryStructureTable {
	return &SalaryStructureTable{
		salaryStructureTable: newSalaryStructureTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newSalaryStructureTableImpl("", "excluded", ""),
	}
}

func newSalaryStructureTableImpl(schemaName, tableName, alias string) salaryStructureTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		EmployeeIdColumn      = postgres.StringColumn("employeeId")
		GrossSalaryColumn     = postgres.FloatColumn("grossSalary")
		CreatedAtColumn       = postgres.TimestampColumn("createdAt")
		UpdatedAtColumn       = postgres.TimestampColumn("updatedAt")
		EmployeeNameColumn    = postgres.StringColumn("employeeName")
		DateOfJoiningColumn   = postgres.DateColumn("dateOfJoining")
		CtcPerMonthColumn     = postgres.FloatColumn("ctcPerMonth")
		DaysPaidColumn        = postgres.FloatColumn("daysPaid")
		SalaryColumn          = postgres.FloatColumn("salary")
		LateColumn            = postgres.FloatColumn("late")
		IncentiveColumn       = postgres.FloatColumn("incentive")
		ConvColumn            = postgres.FloatColumn("conv")
		AdvanceColumn         = postgres.FloatColumn("advance")
		DeductionAmountColumn = postgres.FloatColumn("deductionAmount")
		AccountNoColumn       = postgres.StringColumn("accountNo")
		IfscColumn            = postgres.StringColumn("ifsc")
		PfDeductionColumn     = postgres.FloatColumn("pfDeduction")
		PfUanNumberColumn     = postgres.StringColumn("pfUanNumber")
		LocationColumn        = postgres.StringColumn("location")
		allColumns            = postgres.ColumnList{IDColumn, EmployeeIdColumn, GrossSalaryColumn, CreatedAtColumn, UpdatedAtColumn, EmployeeNameColumn, DateOfJoiningColumn, CtcPerMonthColumn, DaysPaidColumn, SalaryColumn, LateColumn, IncentiveColumn, ConvColumn, AdvanceColumn, DeductionAmountColumn, AccountNoColumn, IfscColumn, PfDeductionColumn, PfUanNumberColumn, LocationColumn}
		mutableColumns        = postgres.ColumnList{EmployeeIdColumn, GrossSalaryColumn, CreatedAtColumn, UpdatedAtColumn, EmployeeNameColumn, DateOfJoiningColumn, CtcPerMonthColumn, DaysPaidColumn, SalaryColumn, LateColumn, IncentiveColumn, ConvColumn, AdvanceColumn, DeductionAmountColumn, AccountNoColumn, IfscColumn, PfDeductionColumn, PfUanNumberColumn, LocationColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, GrossSalaryColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return salaryStructureTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		EmployeeId:      EmployeeIdColumn,
		GrossSalary:     GrossSalaryColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,
		EmployeeName:    EmployeeNameColumn,
		DateOfJoining:   DateOfJoiningColumn,
		CtcPerMonth:     CtcPerMonthColumn,
		DaysPaid:        DaysPaidColumn,
		Salary:          SalaryColumn,
		Late:            LateColumn,
		Incentive:       IncentiveColumn,
		Conv:            ConvColumn,
		Advance:         AdvanceColumn,
		DeductionAmount: DeductionAmountColumn,
		AccountNo:       AccountNoColumn,
		Ifsc:            IfscColumn,
		PfDeduction:     PfDeductionColumn,
		PfUanNumber:     PfUanNumberColumn,
		Location:        LocationColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
